### ISSUE TITLE
Videokwaliteit aanpassen

### ISSUE THREAD

**Issue by Anthirian** [skipmodea1/plugin.video.tweakers#1]
Hoi,

allereerst complimenten voor deze addon. Ik heb hem kort geleden ontdekt in de repository en het werkt erg fijn om de video's op deze manier te bekijken.

Ik vroeg me alleen wel af of het mogelijk is om de video ook in een hogere kwaliteit te kunnen bekijken. Als ik zo door de code heen loop zie ik dat je de video's uit de individuele HTML5 videopagina haalt met BeautifulSoup, maar in de broncode daarvan staan de hogere-kwaliteit videos niet. Met Chrome kun je echter wel bij de developertools onder het tabblad resources zien dat er meerdere beschikbaar zijn. Nu weet ik niet of je hier bij kunt. Als dat wel kan zou het erg tof zijn als het mogelijk is om ook deze video's te kiezen, al dan niet via een extra instelling.

Bedankt!

**Comment by skipmodea1** [comment]
Hallo,

Leuk dat je de addon gebruikt!

Kun je aangeven wat je precies bedoeld met 'Met Chrome kun je echter wel 
bij de developertools onder het tabblad resources zien dat er meerdere 
beschikbaar zijn.'. Een schermprintje zou helpen, dan kan ik wat 
gerichter zoeken.

Groeten

**Comment by Anthirian** [comment]
Ja natuurlijk. 

Allereerst schakel ik op `chrome://plugins` de Adobe Flash Player plugin(s) uit, zodat ik de HTML5 pagina te zien krijg. 
Daarna ga ik naar bijvoorbeeld http://tweakers.net/video/player/8197/sony-vaio-tap-11.html. 
Als ik dan op `F12` druk krijg ik de developer tools te zien.
Als je dan op het tabblad `Resources` klikt krijg je onder `Frame > Paginanaam > Other` de andere kwaliteit video's te zien die er zijn.

![image](https://f.cloud.github.com/assets/704388/1087415/4db8bd7a-1617-11e3-88f8-ed0287354ba7.png)

Hopelijk heb je hier wat aan.

**Comment by ninovanhooff** [comment]
Ondanks dat deze request al meer dan 2 jaar oud is wil ik hem bouwen.Laat maar weten als er behoefte aan is

**Comment by skipmodea1** [comment]
On 10-4-2016 00:07, ninovanhooff wrote:

> Ondanks dat deze request al meer dan 2 jaar oud is wil ik hem 
> bouwen.Laat maar weten als er behoefte aan is
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> https://github.com/skipmodea1/plugin.video.tweakers/issues/1#issuecomment-207863011
> 
> Lijkt me een prima idee.

Misschien is dat zoekgebeuren ook wel simpel te doen 
(http://tweakers.net/video/zoeken/?keyword=<watjezoekt>). Ik heb zoiets 
al in deze addon zitten: 
https://github.com/skipmodea1/plugin.video.worldstarhiphop/. Wellicht 
dat het daar simpel van te jatten is...

---

Dit e-mailbericht is gecontroleerd op virussen met Avast antivirussoftware.
https://www.avast.com/antivirus

**Comment by skipmodea1** [comment]
Ik heb de zoekfunctie toegevoegd
