### ISSUE TITLE
Enkele kleine problemen met deze addon

### ISSUE THREAD

**Issue by keeshoekzema** [skipmodea1/plugin.video.tweakers#4]
Cookie om cookiemuur te omzeilen zijn niet toekomstbestendig, daarom kun je beter de volgende header zetten:
X-Cookies-Accepted: 1

Verder is de UserAgent die je gebruikt een 'gewone' (hele oude) chrome, het zou een stuk beter (en voor ons om problemen met deze addon te ontdekken) om een useragent mee te geven alla:
user_agent "Kodi Mediaplayer $versie / Tweakers Addon $versie"

Ik zie de laatste tijd steeds vaker dat deze addon 'teveel' pageviews doet op Tweakers en daardoor een ban krijgt. Als we ze beter kunnen indentificeren dan is dat probleem beter te onderzoeken.

**Comment by skipmodea1** [comment]
Ik heb een nieuwe versie (1.1.3) gemaakt met o.a. bovenstaande wijzigingen erin. Je kunt het bekijken in de code hier. Ik zal versie 1.1.3 binnenkort naar de kodi repo pushen, ik moet eerst nog wachten totdat 1.1.2 in de officiele repo terecht is gekomen. Als 1.1.3 live is, dan update ik dit issue, dan zie je hier een mailtje van verschijnen.

**Comment by skipmodea1** [comment]
Versie 1.1.3 is nu beschikbaar in kodi. Succes met het onderzoeken van het ban-probleem.
