### ISSUE TITLE
Correctly adding video paramaters

### ISSUE THREAD

**Issue by MartijnKaijser** [skipmodea1/plugin.video.tweakers#5]
I noticed that you added the setContent the incorrect way.
https://github.com/skipmodea1/plugin.video.tweakers/blob/master/resources/lib/tweakers_list.py#L170
should look like
`list_item.setInfo("video", {"title": title, "studio": "Tweakers", "mediatype": "video", "plot": title})`
and drop the line you added below (it's the same in your other plugins)

The thumbnail resolution can also be increased by tweaking the image URL a bit
https://ic.tweakimg.net/img/account=s7JeEm/item=HaQKPcqSABak/size=124x70/image.jpg
to
https://ic.tweakimg.net/img/account=s7JeEm/item=HaQKPcqSABak/size=720x480/image.jpg
Not sure how reliable this is but at least it looks better. You'll probably need to experiment a bit with this as i don't know what is available.

You can also set the playtime as it's available as well.
`<span class="playtime">01:27</span>`
with 
`list_item.setInfo("video", {"duration": 87})`
which can be added to the already used setInfo. So you need to convert the MM:SS to an integer in seconds.

For **plot** your can also scrape the website by using the url provided and get the video description text which would make it a lot nicer to view :)

**Comment by skipmodea1** [comment]
Thanks, that looks doable. I will have a look :)

**Comment by MartijnKaijser** [comment]
You might want to save the plot by storing it in local file per video so you don't need to rescrape the site again and again.

**Comment by skipmodea1** [comment]
I'm using the partial plot that's available on the list of videos.
